// Kervan Kahve - Ürün Veritabanı
// .cursorrules dosyasına uygun olarak tasarlanmıştır

const products = [
  // KAHVE ÜRÜNLERİ - Gerçek fotoğraflarla güncellendi
  {
    id: 1,
    name: "Kervan Kahve Etiyopya",
    brand: "Kervan Kahve",
    productName: "Etiyopya",
    description: "Narenciye ve çiçeksi notalar, özel kavrum",
    category: "espresso",
    roastLevel: "açık",
    origin: "Etiyopya",
    image: "images/coffees/etiyopya.png",
    featured: false,
    weight: "250g",
    tastingNotes: ["narenciye", "çiçeksi", "berrak"]
  },
  {
    id: 2,
    name: "Kervan Kahve Kolombiya",
    brand: "Kervan Kahve",
    productName: "Kolombiya",
    description: "Çikolata ve karamel tatları, mükemmel denge",
    category: "espresso", 
    roastLevel: "orta",
    origin: "Kolombiya",
    image: "images/coffees/kolombiya.png",
    featured: false,
    weight: "250g",
    tastingNotes: ["çikolata", "karamel", "fındık"]
  },
  {
    id: 3,
    name: "Kervan Kahve Guatemala",
    brand: "Kervan Kahve",
    productName: "Guatemala",
    description: "Dumanlı ve baharatlı karakter, zengin gövde",
    category: "espresso",
    roastLevel: "orta-koyu",
    origin: "Guatemala",
    image: "images/coffees/guatemala.png",
    featured: true,
    weight: "250g",
    tastingNotes: ["dumanlı", "baharat", "kakao"]
  },
  {
    id: 4,
    name: "Kervan Kahve Brezilya",
    brand: "Kervan Kahve",
    productName: "Brezilya",
    description: "Yumuşak ve dengeli profil, klasik tat",
    category: "espresso",
    roastLevel: "orta",
    origin: "Brezilya",
    image: "images/coffees/brezilya.png",
    featured: false,
    weight: "250g",
    tastingNotes: ["yumuşak", "dengeli", "çikolata"]
  },
  {
    id: 5,
    name: "Kervan Kahve Kenya",
    brand: "Kervan Kahve",
    productName: "Kenya",
    description: "Asitli ve parlak karakter, wine-like tatlar",
    category: "espresso",
    roastLevel: "orta",
    origin: "Kenya",
    image: "images/coffees/kenya.png",
    featured: false,
    weight: "250g",
    tastingNotes: ["asitli", "parlak", "üzüm"]
  },
  {
    id: 48,
    name: "Kervan Kahve Espresso",
    brand: "Kervan Kahve",
    productName: "Espresso",
    description: "Yoğun aroması ve kremsi dokusuyla mükemmel espresso deneyimi. Profesyonel barista kalitesi.",
    category: "espresso",
    roastLevel: "koyu",
    origin: "Blend",
    image: "images/coffees/espresso-card.webp",
    featured: true,
    weight: "250g",
    tastingNotes: ["yoğun", "kremsi", "bitter"]
  },
  {
    id: 49,
    name: "Kervan Kahve Filtre Kahve",
    brand: "Kervan Kahve",
    productName: "Filtre Kahve",
    description: "Dengeli ve aromatik profiliyle sabah kahvenizin vazgeçilmezi. Yumuşak ve tatmin edici.",
    category: "espresso",
    roastLevel: "orta",
    origin: "Blend",
    image: "images/coffees/filtre-kahve-card.webp",
    featured: true,
    weight: "250g",
    tastingNotes: ["dengeli", "aromatik", "yumuşak"]
  },
  {
    id: 50,
    name: "Kervan Kahve Türk Kahvesi",
    brand: "Kervan Kahve",
    productName: "Türk Kahvesi",
    description: "Geleneksel Türk kahvesi kültürünün en özel hali. Zengin tat ve koku ile damağınızda iz bırakır.",
    category: "espresso",
    roastLevel: "orta-koyu",
    origin: "Blend",
    image: "images/coffees/turk-kahvesi-card.webp",
    featured: true,
    weight: "250g",
    tastingNotes: ["geleneksel", "zengin", "aromatik"]
  },

  // ŞURUP ÜRÜNLERİ - DaVinci Gourmet
  {
    id: 6,
    name: "DaVinci Gourmet Karamel Şurubu",
    brand: "DaVinci Gourmet",
    productName: "Karamel Şurubu",
    description: "İçeceklerinize tatlı karamel aroması",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/davinci-gourmet-karamel-surup.png",
    featured: true,
    volume: "700ml",
    tastingNotes: ["karamel", "tatlı", "kremsi"]
  },
  {
    id: 19,
    name: "DaVinci Gourmet Çilek Şurubu",
    brand: "DaVinci Gourmet",
    productName: "Çilek Şurubu",
    description: "Tatlı çilek aromalı şurup",
    category: "surup",
    subCategory: "meyveli",
    image: "images/syrups/davinci-gourmet-cilek-surup.png",
    featured: true,
    volume: "700ml",
    tastingNotes: ["taze", "tatlı", "aromalı"]
  },
  {
    id: 33,
    name: "DaVinci Gourmet Beyaz Çikolata Şurubu",
    brand: "DaVinci Gourmet",
    productName: "Beyaz Çikolata Şurubu",
    description: "Kremsi beyaz çikolata aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/davinci-gourmet-beyaz-cikolata.png",
    featured: true,
    volume: "700ml",
    tastingNotes: ["kremsi", "tatlı", "vanilya"]
  },
  {
    id: 34,
    name: "DaVinci Gourmet Çikolata Şurubu",
    brand: "DaVinci Gourmet",
    productName: "Çikolata Şurubu",
    description: "Yoğun çikolata aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/davinci-gourmet-cikolata-surup.png",
    featured: true,
    volume: "700ml",
    tastingNotes: ["yoğun", "kakao", "tatlı"]
  },
  {
    id: 35,
    name: "DaVinci Gourmet Vanilya Şurubu",
    brand: "DaVinci Gourmet",
    productName: "Vanilya Şurubu",
    description: "Klasik vanilya aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/davinci-gourmet-vanilya-surup.png",
    featured: true,
    volume: "700ml",
    tastingNotes: ["vanilya", "klasik", "kremsi"]
  },

  // ŞURUP ÜRÜNLERİ - FO Food Products
  {
    id: 51,
    name: "FO Karamel Şurubu",
    brand: "FO",
    productName: "Karamel Şurubu",
    description: "Zengin karamel aromalı profesyonel şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/fo-karamel-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["karamel", "zengin", "tatlı"]
  },
  {
    id: 52,
    name: "FO Çilek Şurubu",
    brand: "FO",
    productName: "Çilek Şurubu",
    description: "Taze çilek aromalı meyveli şurup",
    category: "surup",
    subCategory: "meyveli",
    image: "images/syrups/fo-cilek-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["çilek", "meyveli", "taze"]
  },
  {
    id: 53,
    name: "FO Beyaz Çikolata Şurubu",
    brand: "FO",
    productName: "Beyaz Çikolata Şurubu",
    description: "Kremsi beyaz çikolata aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/fo-beyaz-cikolata-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["beyaz çikolata", "kremsi", "tatlı"]
  },
  {
    id: 54,
    name: "FO Çikolata Şurubu",
    brand: "FO",
    productName: "Çikolata Şurubu",
    description: "Yoğun çikolata aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/fo-cikolata-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["çikolata", "yoğun", "kakao"]
  },
  {
    id: 55,
    name: "FO Vanilya Şurubu",
    brand: "FO",
    productName: "Vanilya Şurubu",
    description: "Klasik vanilya aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/fo-vanilya-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["vanilya", "klasik", "aromatik"]
  },

  // ŞURUP ÜRÜNLERİ - Gusse Şuruplar
  {
    id: 56,
    name: "Gusse Karamel Şurubu",
    brand: "Gusse",
    productName: "Karamel Şurubu",
    description: "Zengin ve kremsi karamel aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/gusse-karamel-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["karamel", "kremsi", "zengin"]
  },
  {
    id: 57,
    name: "Gusse Çilek Şurubu",
    brand: "Gusse",
    productName: "Çilek Şurubu",
    description: "Taze çilek aromalı meyveli şurup",
    category: "surup",
    subCategory: "meyveli",
    image: "images/syrups/gusse-cilek-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["çilek", "meyveli", "taze"]
  },
  {
    id: 58,
    name: "Gusse Beyaz Çikolata Şurubu",
    brand: "Gusse",
    productName: "Beyaz Çikolata Şurubu",
    description: "Kremsi beyaz çikolata aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/gusse-beyaz-cikolata-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["beyaz çikolata", "kremsi", "tatlı"]
  },
  {
    id: 59,
    name: "Gusse Çikolata Şurubu",
    brand: "Gusse",
    productName: "Çikolata Şurubu",
    description: "Yoğun çikolata aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/gusse-cikolata-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["çikolata", "yoğun", "kakao"]
  },
  {
    id: 60,
    name: "Gusse Vanilya Şurubu",
    brand: "Gusse",
    productName: "Vanilya Şurubu",
    description: "Klasik vanilya aromalı şurup",
    category: "surup",
    subCategory: "tatlı",
    image: "images/syrups/gusse-vanilya-surup.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["vanilya", "klasik", "aromatik"]
  },

  // GUSSE SOSLAR - Püre ve Tatlandırıcılar kategorisine taşındı
  {
    id: 40,
    name: "Gusse Beyaz Çikolatalı Sos",
    brand: "Gusse",
    productName: "Beyaz Çikolatalı Sos",
    description: "Kremsi beyaz çikolata aromalı sos",
    category: "pure-tatlandirici",
    subCategory: "sos",
    image: "images/purees-sweeteners/gusse-beyaz-cikolatali-sos.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["kremsi", "vanilya", "tatlı"]
  },
  {
    id: 41,
    name: "Gusse Bitter Çikolatalı Sos",
    brand: "Gusse",
    productName: "Bitter Çikolatalı Sos",
    description: "Yoğun bitter çikolata aromalı sos",
    category: "pure-tatlandirici",
    subCategory: "sos",
    image: "images/purees-sweeteners/gusse-bitter-cikolatali-sos.webp",
    featured: false,
    volume: "700ml",
    tastingNotes: ["bitter", "kakao", "yoğun"]
  },
  {
    id: 42,
    name: "Gusse Çikolatalı Sos",
    brand: "Gusse",
    productName: "Çikolatalı Sos",
    description: "Klasik çikolata aromalı sos",
    category: "pure-tatlandirici",
    subCategory: "sos",
    image: "images/purees-sweeteners/gusse-cikolatali-sos.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["çikolata", "klasik", "dengeli"]
  },
  {
    id: 43,
    name: "Gusse Fındık Sos",
    brand: "Gusse",
    productName: "Fındık Sos",
    description: "Kavrulmuş fındık aromalı sos",
    category: "pure-tatlandirici",
    subCategory: "sos",
    image: "images/purees-sweeteners/gusse-findik-sos.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["fındık", "kavrulmuş", "zengin"]
  },
  {
    id: 44,
    name: "Gusse Frambuaz Meyveli Sos",
    brand: "Gusse",
    productName: "Frambuaz Meyveli Sos",
    description: "Taze frambuaz aromalı meyveli sos",
    category: "pure-tatlandirici",
    subCategory: "sos",
    image: "images/purees-sweeteners/gusse-frambuaz-meyveli-sos.webp",
    featured: false,
    volume: "700ml",
    tastingNotes: ["frambuaz", "meyveli", "asitli"]
  },
  {
    id: 45,
    name: "Gusse Karamel Sos",
    brand: "Gusse",
    productName: "Karamel Sos",
    description: "Kremsi karamel aromalı sos",
    category: "pure-tatlandirici",
    subCategory: "sos",
    image: "images/purees-sweeteners/gusse-karamel-sos.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["karamel", "kremsi", "zengin"]
  },
  {
    id: 46,
    name: "Gusse Sütlü Çikolatalı Sos",
    brand: "Gusse",
    productName: "Sütlü Çikolatalı Sos",
    description: "Sütlü çikolata aromalı sos",
    category: "pure-tatlandirici",
    subCategory: "sos",
    image: "images/purees-sweeteners/gusse-sutlu-cikolatali-sos.webp",
    featured: false,
    volume: "700ml",
    tastingNotes: ["sütlü", "çikolata", "yumuşak"]
  },
  {
    id: 47,
    name: "Gusse Tuzlu Karamel Sos",
    brand: "Gusse",
    productName: "Tuzlu Karamel Sos",
    description: "Tuzlu karamel aromalı özel sos",
    category: "pure-tatlandirici",
    subCategory: "sos",
    image: "images/purees-sweeteners/gusse-tuzlu-karamel-sos.webp",
    featured: true,
    volume: "700ml",
    tastingNotes: ["tuzlu", "karamel", "kontrast"]
  },

  // PÜRE VE TATLANDIRICILAR
  {
    id: 7,
    name: "Montare D'oro Sprey Krema",
    brand: "Montare D'oro",
    productName: "Sprey Krema",
    description: "Kahve ve tatlılar için kremsi sprey",
    category: "pure-tatlandirici",
    subCategory: "krema",
    image: "images/purees-sweeteners/montare-doro-sprey.jpeg", 
    featured: true,
    volume: "250g",
    tastingNotes: ["kremsi", "hafif", "dekoratif"]
  },
  {
    id: 31,
    name: "Bobaco Bubble Tea",
    brand: "Bobaco",
    productName: "Bubble Tea",
    description: "Bubble tea için özel formül karışımı",
    category: "pure-tatlandirici",
    subCategory: "özel",
    image: "images/purees-sweeteners/bobaco-bubble-tea.jpeg",
    featured: true,
    volume: "700ml",
    usageArea: ["bubble tea", "soğuk içecekler", "smoothie"],
    tastingNotes: ["modern", "trend", "çok amaçlı"]
  },

  // TATLI ÜRÜNLERİ
  {
    id: 10,
    name: "DORO CAKE Frambuazlı Cheesecake",
    brand: "DORO CAKE",
    productName: "Frambuazlı Cheesecake",
    description: "Taze frambuazlı cheesecake, kahvenizin mükemmel eşlikçisi",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/frambuazlı-cheesecake.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["labne peyniri", "frambuaz", "bisküvi"],
    tastingNotes: ["kremsi", "asitli", "taze"]
  },
  {
    id: 11,
    name: "DORO CAKE Çikolatalı Pasta",
    brand: "DORO CAKE",
    productName: "Çikolatalı Pasta",
    description: "Yoğun çikolata aromalı özel pasta",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/cikolatalı-pasta-1.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["bitter çikolata", "krema", "kakao"],
    tastingNotes: ["yoğun", "bitter", "zengin"]
  },
  {
    id: 12,
    name: "DORO CAKE Latte Pasta",
    brand: "DORO CAKE",
    productName: "Latte Pasta",
    description: "Kahve aromalı kremali pasta",
    category: "tatli",
    subCategory: "pasta", 
    image: "images/sweets/latte-pasta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["espresso", "mascarpone", "krema"],
    tastingNotes: ["kahveli", "kremsi", "dengeli"]
  },
  {
    id: 13,
    name: "DORO CAKE Portakal Kremalı Pasta",
    brand: "DORO CAKE",
    productName: "Portakal Kremalı Pasta",
    description: "Ferahlatıcı portakal aromalı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/portakalli-kremali-pasta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["portakal", "krema", "bisküvi"],
    tastingNotes: ["ferah", "narenciye", "kremsi"]
  },
  {
    id: 26,
    name: "DORO CAKE Premium Çikolatalı Pasta",
    brand: "DORO CAKE",
    productName: "Premium Çikolatalı Pasta",
    description: "Özel çikolata karışımı ile hazırlanmış pasta",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/cikolotali-pasta-2.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["premium çikolata", "fındık", "krema"],
    tastingNotes: ["premium", "fındıklı", "yumuşak"]
  },
  {
    id: 27,
    name: "DORO CAKE Deluxe Çikolatalı Pasta",
    brand: "DORO CAKE",
    productName: "Deluxe Çikolatalı Pasta",
    description: "Zengin çikolata katmanları ile özel pasta",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/çikolatali-pasta-3.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["bitter çikolata", "sütlü çikolata", "beyaz çikolata"],
    tastingNotes: ["katmanlı", "üçlü", "zengin"]
  },
  {
    id: 28,
    name: "DORO CAKE Frambuazlı Pasta",
    brand: "DORO CAKE",
    productName: "Frambuazlı Pasta",
    description: "Taze frambuaz parçacıklı nefis pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/frambuazli-pasta.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["taze frambuaz", "krema", "pandispanya"],
    tastingNotes: ["meyveli", "taze", "hafif"]
  },
  {
    id: 29,
    name: "DORO CAKE Kırmızı Meyveli Pasta",
    brand: "DORO CAKE",
    productName: "Kırmızı Meyveli Pasta",
    description: "Karışık kırmızı meyveler ile hazırlanmış pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/kirmizi-meyveli-pasta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["çilek", "kiraz", "frambuaz", "krema"],
    tastingNotes: ["karışık", "renkli", "meyveli"]
  },
  {
    id: 30,
    name: "DORO CAKE Krokanlı Çikolatalı Pasta",
    brand: "DORO CAKE",
    productName: "Krokanlı Çikolatalı Pasta",
    description: "Çıtır krokan parçacıklı çikolatalı pasta",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/krokanli-cikolatali-pasta.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["çikolata", "krokan", "fındık ezmesi", "krema"],
    tastingNotes: ["çıtır", "tekstürlü", "fındıklı"]
  },

  // DİLİM TATLILAR - D'Oro
  {
    id: 64,
    name: "DORO CAKE Brownie",
    brand: "DORO CAKE",
    productName: "Brownie",
    description: "Klasik çikolatalı brownie, yoğun kakao tadı",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/brownie.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["bitter çikolata", "kakao", "tereyağı"],
    tastingNotes: ["yoğun", "çikolatalı", "nemli"]
  },
  {
    id: 65,
    name: "DORO CAKE Fıstıklı Albeni",
    brand: "DORO CAKE",
    productName: "Fıstıklı Albeni",
    description: "Antep fıstığı ile kaplı özel albeni",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/fistikli-albeni.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["antep fıstığı", "çikolata", "bisküvi"],
    tastingNotes: ["fıstıklı", "çikolatalı", "çıtır"]
  },
  {
    id: 66,
    name: "DORO CAKE Çikolatalı Sufle",
    brand: "DORO CAKE",
    productName: "Çikolatalı Sufle",
    description: "Sıcak servis edilen akışkan çikolatalı sufle",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/cikolatali-sufle.jpeg",
    featured: true,
    serving: "1 porsiyon",
    ingredients: ["bitter çikolata", "yumurta", "tereyağı"],
    tastingNotes: ["akışkan", "sıcak", "yoğun"]
  },
  {
    id: 67,
    name: "DORO CAKE Red Velvet Pasta",
    brand: "DORO CAKE",
    productName: "Red Velvet Pasta",
    description: "Kırmızı kadife dokusu ile klasik Amerikan pastası",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/red-velvet-pasta.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["kakao", "kırmızı gıda boyası", "cream cheese"],
    tastingNotes: ["kadifemsi", "kremsi", "hafif"]
  },
  {
    id: 68,
    name: "DORO CAKE Vişneli Çikolatalı Pasta",
    brand: "DORO CAKE",
    productName: "Vişneli Çikolatalı Pasta",
    description: "Vişne dolgulu çikolatalı kat pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/visneli-cikolatali-pasta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["vişne", "çikolata", "pudra şekeri"],
    tastingNotes: ["ekşi-tatlı", "meyveli", "çikolatalı"]
  },
  {
    id: 69,
    name: "DORO CAKE Tiramisu",
    brand: "DORO CAKE",
    productName: "Tiramisu",
    description: "İtalyan klasiği, mascarpone kremalı tiramisu",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/tiramisu.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["mascarpone", "espresso", "kakao", "savoiardi"],
    tastingNotes: ["kahveli", "kremsi", "hafif"]
  },
  {
    id: 70,
    name: "DORO CAKE Çikolatalı Karamelli Bar",
    brand: "DORO CAKE",
    productName: "Çikolatalı Karamelli Bar",
    description: "Karamel dolgulu çikolata kaplı bar",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/cikolatali-karamelli-bar.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["sütlü çikolata", "karamel", "fındık"],
    tastingNotes: ["karamelli", "çikolatalı", "fındıklı"]
  },
  {
    id: 71,
    name: "DORO CAKE Yaban Mersinli Cheesecake",
    brand: "DORO CAKE",
    productName: "Yaban Mersinli Cheesecake",
    description: "Yaban mersini soslu kremalı cheesecake",
    category: "tatli",
    subCategory: "cheesecake",
    image: "images/sweets/dilim-tatlilar/yaban-mersinli-cheesecake.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["labne", "yaban mersini", "bisküvi"],
    tastingNotes: ["kremsi", "meyveli", "taze"]
  },
  {
    id: 72,
    name: "DORO CAKE Beyaz Çikolatalı Kalp",
    brand: "DORO CAKE",
    productName: "Beyaz Çikolatalı Kalp",
    description: "Kalp şeklinde beyaz çikolata kaplı pasta",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/beyaz-cikolatali-kalp.jpeg",
    featured: false,
    serving: "1 porsiyon",
    ingredients: ["beyaz çikolata", "krema", "pandispanya"],
    tastingNotes: ["tatlı", "kremsi", "vanilya"]
  },
  {
    id: 73,
    name: "DORO CAKE Fıstıklı Çikolatalı Pasta",
    brand: "DORO CAKE",
    productName: "Fıstıklı Çikolatalı Pasta",
    description: "Antep fıstığı serpilmiş çikolatalı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/fistikli-cikolatali-pasta-1.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["antep fıstığı", "çikolata", "krema"],
    tastingNotes: ["fıstıklı", "çikolatalı", "zengin"]
  },
  {
    id: 74,
    name: "DORO CAKE Fıstıklı Çikolatalı Pasta Premium",
    brand: "DORO CAKE",
    productName: "Fıstıklı Çikolatalı Pasta Premium",
    description: "Katmanlı fıstık ve çikolata kremalı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/fistikli-cikolatali-pasta-2.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["antep fıstığı", "çikolata", "beyaz krema"],
    tastingNotes: ["katmanlı", "fıstıklı", "dengeli"]
  },
  {
    id: 75,
    name: "DORO CAKE Frambuazlı Brownie",
    brand: "DORO CAKE",
    productName: "Frambuazlı Brownie",
    description: "Taze frambuaz ile süslenmiş brownie",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/frambuazli-brownie.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["brownie", "frambuaz", "çikolata"],
    tastingNotes: ["meyveli", "çikolatalı", "yoğun"]
  },
  {
    id: 76,
    name: "DORO CAKE Profiterollü Çikolatalı Pasta",
    brand: "DORO CAKE",
    productName: "Profiterollü Çikolatalı Pasta",
    description: "Profiterol toplarıyla süslü çikolata pastası",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/profiterollu-cikolatali-pasta.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["profiterol", "çikolata kreması", "pandispanya"],
    tastingNotes: ["zengin", "çikolatalı", "katmanlı"]
  },
  {
    id: 77,
    name: "DORO CAKE Orman Meyveli Pasta",
    brand: "DORO CAKE",
    productName: "Orman Meyveli Pasta",
    description: "Karışık orman meyveleri ile hazırlanmış pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/orman-meyveli-pasta-1.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["yaban mersini", "frambuaz", "böğürtlen", "krema"],
    tastingNotes: ["meyveli", "ekşi-tatlı", "renkli"]
  },
  {
    id: 78,
    name: "DORO CAKE Limonlu Haşhaşlı Kek",
    brand: "DORO CAKE",
    productName: "Limonlu Haşhaşlı Kek",
    description: "Limon aromalı haşhaş tohumlu kek",
    category: "tatli",
    subCategory: "kek",
    image: "images/sweets/dilim-tatlilar/limonlu-hashasli-kek.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["limon", "haşhaş", "glazür"],
    tastingNotes: ["narenciye", "çıtır", "hafif"]
  },
  {
    id: 79,
    name: "DORO CAKE Beyaz Çikolatalı Raffaello",
    brand: "DORO CAKE",
    productName: "Beyaz Çikolatalı Raffaello",
    description: "Hindistan cevizi ve beyaz çikolatalı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/beyaz-cikolatali-raffaello.jpeg",
    featured: true,
    serving: "1 porsiyon",
    ingredients: ["beyaz çikolata", "hindistan cevizi", "badem"],
    tastingNotes: ["hindistan cevizi", "beyaz çikolata", "kremsi"]
  },
  {
    id: 80,
    name: "DORO CAKE San Sebastian Cheesecake",
    brand: "DORO CAKE",
    productName: "San Sebastian Cheesecake",
    description: "Bask usulü yanık cheesecake",
    category: "tatli",
    subCategory: "cheesecake",
    image: "images/sweets/dilim-tatlilar/san-sebastian-cheesecake.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["cream cheese", "yumurta", "krema"],
    tastingNotes: ["karamelize", "kremsi", "yoğun"]
  },
  {
    id: 81,
    name: "DORO CAKE Fıstıklı Çikolatalı Pasta Deluxe",
    brand: "DORO CAKE",
    productName: "Fıstıklı Çikolatalı Pasta Deluxe",
    description: "Toz fıstık kaplı çikolatalı özel pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/fistikli-cikolatali-pasta-3.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["antep fıstığı", "çikolata kreması", "pandispanya"],
    tastingNotes: ["fıstıklı", "lüks", "kremsi"]
  },
  {
    id: 82,
    name: "DORO CAKE Limonlu Cheesecake",
    brand: "DORO CAKE",
    productName: "Limonlu Cheesecake",
    description: "Ferahlatıcı limon aromalı cheesecake",
    category: "tatli",
    subCategory: "cheesecake",
    image: "images/sweets/dilim-tatlilar/limonlu-cheesecake.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["labne", "limon", "bisküvi"],
    tastingNotes: ["ekşi", "ferah", "kremsi"]
  },
  {
    id: 83,
    name: "DORO CAKE Vişneli Crumble Turta",
    brand: "DORO CAKE",
    productName: "Vişneli Crumble Turta",
    description: "Vişne dolgulu çıtır hamurlu turta",
    category: "tatli",
    subCategory: "turta",
    image: "images/sweets/dilim-tatlilar/visneli-crumble-turta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["vişne", "crumble", "turta hamuru"],
    tastingNotes: ["meyveli", "çıtır", "ev yapımı"]
  },
  {
    id: 84,
    name: "DORO CAKE Medovik Bal Pasta",
    brand: "DORO CAKE",
    productName: "Medovik Bal Pasta",
    description: "Rus usulü bal kremalı katmanlı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/medovik-bal-pasta.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["bal", "karamel", "bisküvi katmanları"],
    tastingNotes: ["ballı", "karamelli", "katmanlı"]
  },
  {
    id: 85,
    name: "DORO CAKE Sütlü Çikolata Bar",
    brand: "DORO CAKE",
    productName: "Sütlü Çikolata Bar",
    description: "Sütlü çikolata kaplı bar",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/sutlu-cikolata-bar.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["sütlü çikolata", "bisküvi", "fındık"],
    tastingNotes: ["sütlü", "çikolatalı", "tatlı"]
  },
  {
    id: 86,
    name: "DORO CAKE Ferrero Rocher",
    brand: "DORO CAKE",
    productName: "Ferrero Rocher",
    description: "Ferrero Rocher tarzı fındıklı çikolata topları",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/ferrero-rocher.jpeg",
    featured: true,
    serving: "1 porsiyon",
    ingredients: ["fındık", "çikolata", "gofret"],
    tastingNotes: ["fındıklı", "çıtır", "zengin"]
  },
  {
    id: 87,
    name: "DORO CAKE Karaorman Pastası",
    brand: "DORO CAKE",
    productName: "Karaorman Pastası",
    description: "Klasik Black Forest pasta, vişne ve çikolata",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/karaorman-pastasi.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["vişne", "çikolata", "krem şanti", "çikolata talaşı"],
    tastingNotes: ["vişneli", "çikolatalı", "klasik"]
  },
  {
    id: 88,
    name: "DORO CAKE Fındıklı Çikolatalı Pasta",
    brand: "DORO CAKE",
    productName: "Fındıklı Çikolatalı Pasta",
    description: "Fındık kremalı çikolata kaplı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/findikli-cikolatali-pasta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["fındık kreması", "çikolata", "krem şanti"],
    tastingNotes: ["fındıklı", "kremsi", "tatlı"]
  },
  {
    id: 89,
    name: "DORO CAKE Frambuazlı Katmanlı Pasta",
    brand: "DORO CAKE",
    productName: "Frambuazlı Katmanlı Pasta",
    description: "Frambuaz kremalı çok katmanlı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/frambuazli-katmanli-pasta.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["frambuaz", "vanilyalı krema", "pandispanya"],
    tastingNotes: ["meyveli", "hafif", "kremsi"]
  },
  {
    id: 90,
    name: "DORO CAKE Kırmızı Kadife Albeni",
    brand: "DORO CAKE",
    productName: "Kırmızı Kadife Albeni",
    description: "Red velvet tarzı kırmızı albeni",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/kirmizi-kadife-albeni.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["kırmızı kadife kek", "çikolata", "fıstık"],
    tastingNotes: ["kadifemsi", "çikolatalı", "renkli"]
  },
  {
    id: 91,
    name: "DORO CAKE Esterhazy Cevizli Pasta",
    brand: "DORO CAKE",
    productName: "Esterhazy Cevizli Pasta",
    description: "Macar klasiği cevizli katmanlı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/esterhazy-cevizli-pasta.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["ceviz", "vanilyalı krema", "fondant"],
    tastingNotes: ["cevizli", "kremsi", "zarif"]
  },
  {
    id: 92,
    name: "DORO CAKE Karamelli Sufle",
    brand: "DORO CAKE",
    productName: "Karamelli Sufle",
    description: "Karamel dolgulu sıcak sufle",
    category: "tatli",
    subCategory: "sufle",
    image: "images/sweets/dilim-tatlilar/karamelli-sufle.jpeg",
    featured: true,
    serving: "1 porsiyon",
    ingredients: ["karamel", "tereyağı", "yumurta"],
    tastingNotes: ["karamelli", "akışkan", "sıcak"]
  },
  {
    id: 93,
    name: "DORO CAKE Bal Karamel Pasta",
    brand: "DORO CAKE",
    productName: "Bal Karamel Pasta",
    description: "Bal ve karamel aromalı katmanlı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/bal-karamel-pasta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["bal", "karamel", "krema"],
    tastingNotes: ["ballı", "karamelli", "yumuşak"]
  },
  {
    id: 94,
    name: "DORO CAKE Çilekli Cheesecake",
    brand: "DORO CAKE",
    productName: "Çilekli Cheesecake",
    description: "Çilek soslu klasik cheesecake",
    category: "tatli",
    subCategory: "cheesecake",
    image: "images/sweets/dilim-tatlilar/cilekli-cheesecake.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["labne", "çilek", "bisküvi"],
    tastingNotes: ["meyveli", "kremsi", "taze"]
  },
  {
    id: 95,
    name: "DORO CAKE Çikolatalı Toplu Brownie",
    brand: "DORO CAKE",
    productName: "Çikolatalı Toplu Brownie",
    description: "Çikolata topları ile süslenmiş brownie",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/cikolatali-toplu-brownie.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["brownie", "çikolata topları", "ganaj"],
    tastingNotes: ["yoğun", "çikolatalı", "zengin"]
  },
  {
    id: 96,
    name: "DORO CAKE Havuçlu Kek",
    brand: "DORO CAKE",
    productName: "Havuçlu Kek",
    description: "Cream cheese kremalı havuçlu kek",
    category: "tatli",
    subCategory: "kek",
    image: "images/sweets/dilim-tatlilar/havuclu-kek.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["havuç", "ceviz", "cream cheese", "tarçın"],
    tastingNotes: ["baharatlı", "kremsi", "nemli"]
  },
  {
    id: 97,
    name: "DORO CAKE Mangolu Cheesecake",
    brand: "DORO CAKE",
    productName: "Mangolu Cheesecake",
    description: "Tropikal mango soslu cheesecake",
    category: "tatli",
    subCategory: "cheesecake",
    image: "images/sweets/dilim-tatlilar/mangolu-cheesecake.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["labne", "mango", "bisküvi"],
    tastingNotes: ["tropikal", "tatlı", "kremsi"]
  },
  {
    id: 98,
    name: "DORO CAKE Yaban Mersinli Pasta",
    brand: "DORO CAKE",
    productName: "Yaban Mersinli Pasta",
    description: "Yaban mersini ile süslenmiş katmanlı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/yaban-mersinli-pasta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["yaban mersini", "krema", "pandispanya"],
    tastingNotes: ["meyveli", "hafif", "renkli"]
  },
  {
    id: 99,
    name: "DORO CAKE Yaban Mersinli Cheesecake Premium",
    brand: "DORO CAKE",
    productName: "Yaban Mersinli Cheesecake Premium",
    description: "Yaban mersini soslu premium cheesecake",
    category: "tatli",
    subCategory: "cheesecake",
    image: "images/sweets/dilim-tatlilar/yaban-mersinli-cheesecake-2.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["labne", "yaban mersini sosu", "bisküvi"],
    tastingNotes: ["meyveli", "yoğun", "kremsi"]
  },
  {
    id: 100,
    name: "DORO CAKE Orman Meyveli Pasta Premium",
    brand: "DORO CAKE",
    productName: "Orman Meyveli Pasta Premium",
    description: "Bol orman meyveli özel pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/orman-meyveli-pasta-2.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["karışık orman meyveleri", "krema", "pandispanya"],
    tastingNotes: ["meyveli", "renkli", "taze"]
  },
  {
    id: 101,
    name: "DORO CAKE Fıstıklı Katmanlı Pasta",
    brand: "DORO CAKE",
    productName: "Fıstıklı Katmanlı Pasta",
    description: "Fıstık kremalı çok katmanlı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/fistikli-katmanli-pasta.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["antep fıstığı", "fıstık kreması", "pandispanya"],
    tastingNotes: ["fıstıklı", "katmanlı", "zengin"]
  },
  {
    id: 102,
    name: "DORO CAKE Vişneli Kremalı Pasta",
    brand: "DORO CAKE",
    productName: "Vişneli Kremalı Pasta",
    description: "Vişne dolgulu krema kaplı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/visneli-kremali-pasta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["vişne", "vanilyalı krema", "crumble"],
    tastingNotes: ["meyveli", "kremsi", "hafif"]
  },
  {
    id: 103,
    name: "DORO CAKE Mermer Kek",
    brand: "DORO CAKE",
    productName: "Mermer Kek",
    description: "Vanilyalı ve kakaolu mermer desenli kek",
    category: "tatli",
    subCategory: "kek",
    image: "images/sweets/dilim-tatlilar/mermer-kek.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["vanilya", "kakao", "tereyağı"],
    tastingNotes: ["klasik", "dengeli", "yumuşak"]
  },
  {
    id: 104,
    name: "DORO CAKE Mozaik Pasta",
    brand: "DORO CAKE",
    productName: "Mozaik Pasta",
    description: "Bisküvili çikolatalı klasik mozaik pasta",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/mozaik-pasta.jpeg",
    featured: true,
    serving: "1 dilim",
    ingredients: ["bisküvi", "çikolata", "tereyağı"],
    tastingNotes: ["klasik", "çıtır", "çikolatalı"]
  },
  {
    id: 105,
    name: "DORO CAKE Çikolatalı Fındıklı Bar",
    brand: "DORO CAKE",
    productName: "Çikolatalı Fındıklı Bar",
    description: "Fındık parçacıklı çikolata bar",
    category: "tatli",
    subCategory: "çikolata",
    image: "images/sweets/dilim-tatlilar/cikolatali-findikli-bar.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["çikolata kreması", "fındık", "red velvet"],
    tastingNotes: ["fındıklı", "çikolatalı", "yoğun"]
  },
  {
    id: 107,
    name: "DORO CAKE Frambuazlı Cheesecake Premium",
    brand: "DORO CAKE",
    productName: "Frambuazlı Cheesecake Premium",
    description: "Frambuaz soslu premium cheesecake",
    category: "tatli",
    subCategory: "cheesecake",
    image: "images/sweets/dilim-tatlilar/frambuazli-cheesecake.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["labne", "frambuaz", "bisküvi"],
    tastingNotes: ["meyveli", "hafif ekşi", "kremsi"]
  },
  {
    id: 108,
    name: "DORO CAKE Çikolatalı Kremalı Pasta",
    brand: "DORO CAKE",
    productName: "Çikolatalı Kremalı Pasta",
    description: "Çikolata kremalı katmanlı pasta",
    category: "tatli",
    subCategory: "pasta",
    image: "images/sweets/dilim-tatlilar/cikolatali-kremali-pasta.jpeg",
    featured: false,
    serving: "1 dilim",
    ingredients: ["çikolata kreması", "pandispanya", "ganaj"],
    tastingNotes: ["kremsi", "çikolatalı", "yumuşak"]
  },

  // AKSESUAR ÜRÜNLERİ
  {
    id: 14,
    name: "Vosco Küp Buz Makinesi VSC-23CG",
    brand: "Vosco",
    productName: "Küp Buz Makinesi VSC-23CG",
    description: "23 kg/gün kapasiteli küp buz makinesi",
    category: "aksesuar",
    subCategory: "makine",
    image: "images/accessories/buz_makinesi.jpg",
    featured: true,
    tastingNotes: ["yüksek kapasite", "küp buz", "profesyonel"]
  },
  {
    id: 15,
    name: "Reneka OEM 2 Grup Espresso Makinesi",
    brand: "Reneka",
    productName: "OEM 2 Grup Espresso Makinesi",
    description: "Profesyonel 2 gruplu espresso makinesi",
    category: "aksesuar",
    subCategory: "makine",
    image: "images/accessories/cimbali.jpg",
    featured: true,
    tastingNotes: ["2 grup", "profesyonel", "yüksek performans"]
  },
  {
    id: 16,
    name: "Fiorenzato F64E Kahve Değirmeni",
    brand: "Fiorenzato",
    productName: "F64E Kahve Değirmeni",
    description: "On demand profesyonel kahve değirmeni",
    category: "aksesuar",
    subCategory: "degirmen",
    image: "images/accessories/kahve_ogutme.jpg",
    featured: true,
    tastingNotes: ["on demand", "hassas öğütme", "profesyonel"]
  },
  {
    id: 61,
    name: "Profesyonel Portafiltre",
    brand: "Kervan Kahve",
    productName: "Portafiltre",
    description: "Espresso makinesi için portafiltre",
    category: "aksesuar",
    subCategory: "aksesuar",
    image: "images/accessories/portafiltre.jpg",
    featured: false,
    tastingNotes: ["paslanmaz çelik", "ergonomik", "dayanıklı"]
  },
  {
    id: 62,
    name: "Samixir Twin Soğuk İçecek Dispenseri",
    brand: "Samixir",
    productName: "Twin Soğuk İçecek Dispenseri",
    description: "20+20 L fıskiyeli ve karıştırıcılı dispenser",
    category: "aksesuar",
    subCategory: "dispenser",
    image: "images/accessories/şerbetlik.jpg",
    featured: true,
    tastingNotes: ["40 L toplam", "fıskiyeli", "karıştırıcılı"]
  },
  {
    id: 63,
    name: "Profesyonel Tamper",
    brand: "Kervan Kahve",
    productName: "Tamper",
    description: "Espresso hazırlığı için profesyonel tamper",
    category: "aksesuar",
    subCategory: "aksesuar",
    image: "images/accessories/tamper.jpg",
    featured: false,
    tastingNotes: ["ergonomik", "ağırlıklı", "paslanmaz"]
  },
  {
    id: 36,
    name: "Vosco Bar Blender 2 Lt",
    brand: "Vosco",
    productName: "Bar Blender 2 Lt",
    description: "Manuel buz kırıcılı 2000W bar blender",
    category: "aksesuar",
    subCategory: "blender",
    image: "images/accessories/vosco_1.jpg",
    featured: false,
    tastingNotes: ["2000W", "buz kırıcı", "manuel"]
  },
  {
    id: 37,
    name: "Vosco VHS-602CG Dijital Bar Blender",
    brand: "Vosco",
    productName: "VHS-602CG Dijital Bar Blender",
    description: "3 Lt dijital bar blender pro",
    category: "aksesuar",
    subCategory: "blender",
    image: "images/accessories/vosco2.jpg",
    featured: true,
    tastingNotes: ["3 Lt", "dijital", "profesyonel"]
  },

  // BİTKİ ÇAYI ÜRÜNLERİ
  {
    id: 20,
    name: "Kervan Kahve Yeşil Çay",
    brand: "Kervan Kahve",
    productName: "Yeşil Çay",
    description: "Antioksidan açısından zengin, ferahlatıcı yeşil çay",
    category: "cay",
    subCategory: "klasik",
    image: "images/teas/yesil-cay.webp",
    featured: true,
    origin: "Çin",
    brewingTime: "2-3 dakika",
    temperature: "80°C",
    healthBenefits: ["antioksidan", "metabolizma hızlandırıcı", "zihin açıcı"],
    tastingNotes: ["ferah", "otsu", "hafif"]
  },
  {
    id: 21,
    name: "Kervan Kahve Elma Tarçın Çayı",
    brand: "Kervan Kahve",
    productName: "Elma Tarçın Çayı",
    description: "Sıcak ve baharatlı elma tarçın karışımı",
    category: "cay",
    subCategory: "aromalı",
    image: "images/teas/elma-tarcin-cayi.webp",
    featured: true,
    origin: "Karma",
    brewingTime: "5-7 dakika",
    temperature: "95°C",
    healthBenefits: ["sindirim destekleyici", "kan şekeri dengeleyici", "ısıtıcı"],
    tastingNotes: ["baharatlı", "tatlı", "ısıtıcı"]
  },
  {
    id: 22,
    name: "Kervan Kahve Kış Çayı",
    brand: "Kervan Kahve",
    productName: "Kış Çayı",
    description: "Kış ayları için özel baharatlı karışım",
    category: "cay",
    subCategory: "mevsimlik",
    image: "images/teas/kis-cayi.webp",
    featured: false,
    origin: "Karma",
    brewingTime: "5-6 dakika",
    temperature: "95°C",
    healthBenefits: ["bağışıklık güçlendirici", "ısıtıcı", "rahatlatıcı"],
    tastingNotes: ["mevsimlik", "baharatlı", "güçlü"]
  },
  {
    id: 23,
    name: "Kervan Kahve Kuşburnu Çayı",
    brand: "Kervan Kahve",
    productName: "Kuşburnu Çayı",
    description: "C vitamini açısından zengin kuşburnu çayı",
    category: "cay",
    subCategory: "bitki",
    image: "images/teas/kusburnu-cayi.webp",
    featured: false,
    origin: "Anadolu",
    brewingTime: "8-10 dakika",
    temperature: "95°C",
    healthBenefits: ["C vitamini", "bağışıklık güçlendirici", "antioksidan"],
    tastingNotes: ["asitli", "doğal", "vitamini"]
  },
  {
    id: 24,
    name: "Kervan Kahve Ihlamur Çayı",
    brand: "Kervan Kahve",
    productName: "Ihlamur Çayı",
    description: "Rahatlatıcı ve sakinleştirici ıhlamur çayı",
    category: "cay",
    subCategory: "bitki",
    image: "images/teas/ihlamur-cayi.webp",
    featured: false,
    origin: "Anadolu",
    brewingTime: "5-7 dakika",
    temperature: "90°C",
    healthBenefits: ["rahatlatıcı", "uyku kalitesi artırıcı", "strés azaltıcı"],
    tastingNotes: ["sakinleştirici", "çiçeksi", "yumuşak"]
  },
  {
    id: 25,
    name: "Kervan Kahve Nane Limon Çayı",
    brand: "Kervan Kahve",
    productName: "Nane Limon Çayı",
    description: "Ferahlatıcı nane ve limon karışımı",
    category: "cay",
    subCategory: "aromalı",
    image: "images/teas/nane-limon-cayi.webp",
    featured: true,
    origin: "Karma",
    brewingTime: "3-5 dakika",
    temperature: "85°C",
    healthBenefits: ["sindirim destekleyici", "ferahlatıcı", "detoks"],
    tastingNotes: ["ferahlatıcı", "narenciye", "mentol"]
  }
];

// Kategori tanımları
const categories = {
  "espresso": {
    name: "Espresso",
    description: "Tüm kahve çeşitleri - Espresso, filtre kahve ve özel karışımlar"
  },
  "surup": {
    name: "Şuruplar",
    description: "İçecek şurupları ve soslar"
  },
  "pure-tatlandirici": {
    name: "Püre ve Tatlandırıcılar",
    description: "Bubble tea, meyveli soslar ve özel tatlandırıcılar"
  },
  "tatli": {
    name: "Tatlılar",
    description: "Ev yapımı tatlı ve atıştırmalıklar"
  },
  "aksesuar": {
    name: "Aksesuarlar", 
    description: "Kahve demleme ekipmanları ve aksesuarlar"
  },
  "cay": {
    name: "Bitki Çayları",
    description: "Doğal ve aromalı bitki çayı çeşitleri"
  }
};

// Kavurma seviyesi tanımları
const roastLevels = {
  "acik": {
    name: "Açık Kavurma",
    description: "Asidik ve parlak tatlar"
  },
  "orta": {
    name: "Orta Kavurma", 
    description: "Dengeli ve yumuşak profil"
  },
  "orta-koyu": {
    name: "Orta-Koyu Kavurma",
    description: "Karamelize notalar"
  },
  "koyu": {
    name: "Koyu Kavurma",
    description: "Yoğun ve güçlü karakter"
  }
};

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { products, categories, roastLevels };
} 